### ISSUE TITLE
Initializing DJ problem

### ISSUE THREAD

**Issue by Rexarus** [Guichaguri/DiscordDJ#11]
Hi, I've been having a problem with the bot, it runs fine up until the "Initializing DJ in..." phase where it just stops,  I know that it isn't finished and just want to know if its something I've missed or whether this is intentional ? 

Thanks for all your hard work by the way!

**Comment by Guichaguri** [comment]
As I've mentioned multiple times, the bot is still "work in progress".
If you want, I'll tell you when the bot is released

**Comment by Guichaguri** [comment]
The first **development** build was released.
