### ISSUE TITLE
Issue with more then one song and skipping

### ISSUE THREAD

**Issue by Ancientblue** [Guichaguri/DiscordDJ#13]
Any help would be appreciated:
Basically I've got the bot working, playing music with !yt linkhere 
However it once the first song has played it won't respond to any other songs.
This is what it looks like in the console: http://prntscr.com/9oucrh
Additionally if somebody does !skip or !next (or with a / instead of !) it gives this error http://prntscr.com/9oudaq

Thanks!

**Comment by Guichaguri** [comment]
These are all known. As you can see, the project is still work in progress.

**Comment by Ancientblue** [comment]
Okay thank you, was just worried it was just me. Please keep up the awesome work :D

**Comment by Guichaguri** [comment]
If you want, I can tell you when its released

**Comment by Ancientblue** [comment]
Yeah, that'd be great.

**Comment by ripcrispy** [comment]
Cool. I was just about to ask about this issue. Good luck in sorting out this issue. :)

**Comment by Guichaguri** [comment]
The first **development** build was released. It's not stable, but it works :)
