### ISSUE TITLE
Bot Not Initializing (again)

### ISSUE THREAD

**Issue by dragsta** [Guichaguri/DiscordDJ#14]
I don't know what causes this but it was fixed with the commit from a few days back and broke with the one from a few hours ago, Just so you know :)

**Comment by Guichaguri** [comment]
I know that. The bot is not released yet, it's not stable and sometimes not even runnable. It's WIP.
If you want, I can tell you when i release it

**Comment by Tomiaz** [comment]
@Guichaguri please notify me as well when you release it.

**Comment by Guichaguri** [comment]
The first **development** build was released.
