### ISSUE TITLE
How much longer

### ISSUE THREAD

**Issue by ShiftBladez** [Guichaguri/DiscordDJ#15]
Can we have an approximate date if possible on when you can give us a downloadable copy, cuz as it is right now the features should be fine the rest can come another patch

**Comment by Legacy47** [comment]
Yes, I would also like to know :+1:

**Comment by Guichaguri** [comment]
There still are some features that I would like to implement. Should I open to beta?

**Comment by ShiftBladez** [comment]
Yes you should, that'd be amazing thx

**Comment by Tomiaz** [comment]
Please do

**Comment by studDUGY** [comment]
Been waiting patiently since the readme update... Please release a beta version! :)

**Comment by Legacy47** [comment]
Great Idea :+1:

**Comment by Guichaguri** [comment]
Here it is: https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.2
**Expect broken stuff**

I still have to document stuff, not all features will work right out the bat, you have to enable them in the config file.
The API is still going to change, you should not use it yet.
Like I already said before, I will implement more features, but feel free to open new issues for bug reports, suggestions or questions.
I will update it as soon as possible with bug fixes, features and more documentation

**Comment by Guichaguri** [comment]
After installing it, it should crash. That's because Discordie have not updated yet.
Open `node_modules/discordie/lib/index.js` in a text editor (such as notepad++) and add `Discordie.Permissions = Constants.Permissions;` before `module.exports = Discordie;`

**Comment by Guichaguri** [comment]
If it says "Encoder not found", it's my fault. You can either [install FFmpeg](http://www.wikihow.com/Install-FFmpeg-on-Windows) or wait until tomorrow for the next update =P

**Comment by Guichaguri** [comment]
I don't have enough time today, so I can't fix those bugs now
Tomorrow I'll start the documentation and release another build
