### ISSUE TITLE
dev Build

### ISSUE THREAD

**Issue by Adrion** [Guichaguri/DiscordDJ#16]
Unexpected Token > in DiscordDJ.js 
You have some weird affectation `c => c.id` 
I don't think that's correct in JS

Good initiative btw. ^^
Hope I'll find some time to spare on the project to help you :)

**Comment by Guichaguri** [comment]
It's the new [arrow functions](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Functions/Arrow_functions) from ECMA 6
You will probably need to update Node.js to [support ECMA 6](https://nodejs.org/en/docs/es6/)
