### ISSUE TITLE
bash script issues. 

### ISSUE THREAD

**Issue by Dazzuh** [Guichaguri/DiscordDJ#17]
~~Hey, the issue with the bot not Initializing has come up a few times in the past, and it's still doing the same thing for me, tested this on both linux and windows.~~
Just read your post on #15 and works after editing discordie. 

second issue, none of the two bash scripts seem to work.

./setup-bot.sh: 

```bash
setup-bot.sh:

 line 2: $'\r': command not found
setup-bot.sh: line 3: syntax error near unexpected token `$'{\r''
'etup-bot.sh: line 3: `function end {
```
./start-bot.sh

```bash
module.js:328
    throw err;
    ^

'rror: Cannot find module '/home/dazzuh/discorddj/runtime/DiscordDJ.js
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
Press [Enter] to close...

**Comment by Guichaguri** [comment]
The start-bot does not works because the bot was not installed correctly, I'll look into the setup-bot

**Comment by Dazzuh** [comment]
The bot starts fine if I run node DiscordDJ.js manually from the runtime folder, just not though the start script.

**Comment by Guichaguri** [comment]
It looks like the line endings were in CRLF (Windows) instead of LF (Unix). I discovered Git replaces LF to CRLF in text files, so I had to disable that.
Try [v0.0.3](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.3) to see if it works now

**Comment by Dazzuh** [comment]
Works perfectly now, thanks!
