### ISSUE TITLE
FFMPEG

### ISSUE THREAD

**Issue by ShiftBladez** [Guichaguri/DiscordDJ#19]
I dont whats wrong but when i launch the application it launches the command prompt box then it disappears and i know it didnt install so help ?

**Comment by Guichaguri** [comment]
Can you provide more information?
I can't help you without it

**Comment by ShiftBladez** [comment]
So in the windows with ffmpeg i went into ffmpeg folder and clicked on all the applications and for each one once i tried to open in it a black box would blink on my screen and disappear, thats for all 3 applications in their

**Comment by ShiftBladez** [comment]
and when i do setupbot is asks to install ffmpeg or libav

**Comment by ShiftBladez** [comment]
but as i said previously that doesnt seem to work

**Comment by Chay8** [comment]
You don't do it that way setupbot will ask for a directory you point it to the bin\ffmpeg none of the other depending n where you installed it, the directory should look like C:ffmpeg\bin\ffmpeg

**Comment by ShiftBladez** [comment]
Um let me try it when I can get back to you

**Comment by ShiftBladez** [comment]
And then get back to you *

**Comment by Guichaguri** [comment]
Yes, you have to open `setup-bot.bat`, wait for the setup to finish and then open `start-bot.bat` to start the bot.

**Comment by ShiftBladez** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/16998918/12831354/c8ee66b4-cb61-11e5-8da7-7047d694528c.png)

**Comment by ShiftBladez** [comment]
oh nvm i had quotations thx soo much <3

**Comment by ShiftBladez** [comment]
um while im already here once the bot is initializing in a chat room can i reconnect or do i wait till initializing is done or what

**Comment by Guichaguri** [comment]
Can you explain better what you are trying to do?
Also, I think you are using v0.0.2, I recommend you updating to v0.0.3

**Comment by ShiftBladez** [comment]
Um ok i will check wat version once i launch the start up bot it says initializing for the bic man (thats my voice channel)

**Comment by ShiftBladez** [comment]
![screenshot 7](https://cloud.githubusercontent.com/assets/16998918/12834001/457e4aae-cb72-11e5-949f-32aacfe0c6ac.png)

**Comment by ShiftBladez** [comment]
this is what happens when i type /youtube (insert url)

**Comment by Guichaguri** [comment]
I'll look into it. For now you can use /add instead

**Comment by ShiftBladez** [comment]
same thing happens for /add, i'll wait till you find out wats wrong
