### ISSUE TITLE
Suggestion: Set file command access permission.

### ISSUE THREAD

**Issue by luckcolors** [Guichaguri/DiscordDJ#24]
Hello.
I currently installed your bot and it's fantastic it works great.
But i have two security features which i think are required:
1. Configuralble permissions: maybe you already have this but i haven't found anything on the wiki
2. Access only certain paths as i would not like for people to randomly accessign every files.
Thanks in advance :P.

**Comment by Guichaguri** [comment]
Thanks :)

1. What do you mean by "security permissions"? The permissions will be configurable in the future, so you can configure to only certain roles be able to run a command or only who has the Talk permission can run another command. I don't know if I my explanation was clear enough
2. Currently, only people with Mute permission can request files by default.

**Comment by luckcolors** [comment]
Yeah sorry. I meant the configurable permissions.

**Comment by luckcolors** [comment]
Also actually will be possible to set in the future config permission for a certain user?

**Comment by Guichaguri** [comment]
I was not thinking about that, but now that you've mentioned it, yes

**Comment by luckcolors** [comment]
I'm closing this for now, feel free to reopen in case you're still interested.
