### ISSUE TITLE
Suggestion: Support for chiptunes files.

### ISSUE THREAD

**Issue by luckcolors** [Guichaguri/DiscordDJ#25]
Another cool thing to support will be the ability to play chiptunes for that there http://lib.openmpt.org/libopenmpt/ is compilable using emscripten to javascript (here's a wrapper for web browsers 
https://github.com/deskjet/chiptune2.js.git ) this will be ofcourse an extension for the /files command.
Of course this is a long term request.

**Comment by Guichaguri** [comment]
FFmpeg doesn't support Module Files/Tracker Music/Chiptunes.
I'm looking into two solutions:

* Extending Chiptune2.js to include Node.js support. It will require the approval of the original Chiptune2.js developer
* Using `openmpt123`. A command-line decoder made by OpenMPT. It should be easier to implement and maintain, but it has no documentation.

**Comment by Guichaguri** [comment]
Update: I was talking with the Chiptune2.js developer, and he said it would better be another project the support for Node.js, and he helped me understand how libopenmpt works as well
So I worked this whole day trying to understand how libopenmpt works and how to use it. I will release the module tomorrow after I implement two more features, then I just need to integrate DiscordDJ with it :)

**Comment by luckcolors** [comment]
Thank you :P.

**Comment by luckcolors** [comment]
Also i wantrd to let you know that i discovered that ffmpeg is actually able to read chiptune files.
You can use this test command: ffmpeg -i chiptunefiles -codec:a libmp3lame -qscale:a 2 output.mp3
Also it seems that ffmpeg uses openmodplug library to decode.

**Comment by Guichaguri** [comment]
But that is only for local files and without information like title, artist, duration and message. It doesn't work with URLs and other stuff like that.
Also, I've just finished the node-chiptune library, it makes no sense to not use it :P

**Comment by luckcolors** [comment]
Yeah sorry about discovering that now :P.
But well a libopenmtp nodejs library is always handy. :D

**Comment by luckcolors** [comment]
I'm closing this for now, feel free to reopen in case you're still interested.
