### ISSUE TITLE
Bug: Crash when command /file gets a not valid / not existing file path.

### ISSUE THREAD

**Issue by luckcolors** [Guichaguri/DiscordDJ#26]
Error log:
``
      events.js:154
      throw er; // Unhandled 'error' event
      ^
``
I hope it helps.

**Comment by Guichaguri** [comment]
Fixed in 99ab4f8

**Comment by Guichaguri** [comment]
[v0.0.4](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.4) was released with the fix
