### ISSUE TITLE
DiscordDJ - Using a playlist

### ISSUE THREAD

**Issue by RayKurzweil** [Guichaguri/DiscordDJ#27]
First off; fantastic work with the bot thus far, easily the most accessible to the inexperienced user such as myself.

I'm curious if you have playlist support in yet, and if so, how exactly do I engage it? I've looked through most of the code and I can't seem to figure it out by myself if its a thing yet or not.

In any case, keep up the good work.

**Comment by Guichaguri** [comment]
It works, but it does not load a playlist from the config yet

**Comment by Guichaguri** [comment]
Playlists are now usable in [v0.0.4](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.4) (4b69ea2eeaa92bebbac235381e0f6310c7f720d2)
Just set the mode type to `playlist`
