### ISSUE TITLE
Bug: A directory with a 'space' in it is considered invalid

### ISSUE THREAD

**Issue by RayKurzweil** [Guichaguri/DiscordDJ#28]
Trying to play a file via a directory with a space within it causes the bot to error and crash.

Example: F:\User\Folder With A Space In Its Name\song.mp3

**Comment by Guichaguri** [comment]
Fixed in 99ab4f8

**Comment by Guichaguri** [comment]
[v0.0.4](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.4) was released with the fix
