### ISSUE TITLE
Install guide?

### ISSUE THREAD

**Issue by SuperDerpy** [Guichaguri/DiscordDJ#3]
Sorry this isn't much an issue as it is me being dumb but could you explain how to use this, I'd really love to try it out.

**Comment by Aiden3043** [comment]
It's as simple as editing **Bots.json** to add in credentials for a bot account and the channel it should connect to. Then, run the appropriate **start-bot** file. Let me know if you encounter any other issues.

**Comment by Guichaguri** [comment]
The installation is a bit complicated, I'm still thinking how I should make the installation easier.
`node-opus` also have problems with Windows, I have to fix that too.
I'll send instructions once the "installer" is done

**Comment by SuperDerpy** [comment]
Okay well thank you I appreciate it. :p

**Comment by SuperDerpy** [comment]
Also to Aiden when I run the bot start.bat it says it can't find module "discord-dj.js" and I have node -npm

**Comment by Shuttle099** [comment]
Same issue here.

**Comment by Khalid34ktt** [comment]
Same here!

**Comment by JoecakeGameDev** [comment]
same. plz fix!

**Comment by Guichaguri** [comment]
The first **development** build was released. It's not stable, but it works :)
