### ISSUE TITLE
Initial Song/Playlist/Radio

### ISSUE THREAD

**Issue by nDiVinEx** [Guichaguri/DiscordDJ#32]
@Guichaguri is it possible so that the first time you launch the bot it instantly plays a playlist or in my case a station?

How exactly do we play a playlist? I've read a couple of other "issues" but nothing mentions on how to actually play a playlist. Say I wanted to play this "https://www.youtube.com/playlist?list=PLx0sYbCqOb8Q_CLZC2BdBSKEEB59BOPUM". How would I do that?

**Comment by Guichaguri** [comment]
Playlists are working, but they are not loadable from the config yet. I'll work on that for the next version

**Comment by nDiVinEx** [comment]
@Guichaguri I don't think you understand what I'm saying. **How**. How exactly do I load the playlists? Look at my example above. If I was to use that link as a playlist, what would I need to do?

**Comment by Guichaguri** [comment]
As I've said, they work, but there's no way to load them yet

**Comment by nDiVinEx** [comment]
@Guichaguri Makes much more sense when you say it like that rather than saying it's not loadable from the config. Thanks for the heads up anyway. Do you have an idea of when the next update will be? I noticed that using radio streams cuts off after about 10 minutes too. I presume that is something you'll fix?

**Comment by Guichaguri** [comment]
Yes, that is something I still have to do.
I'll add commands and config options for playlists, support for chiptunes and soundcloud configurable API keys in the next version. It will probably be released today or tomorrow

**Comment by Guichaguri** [comment]
Playlist Mode is now usable in [v0.0.4](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.4) (4b69ea2eeaa92bebbac235381e0f6310c7f720d2)
Just set the mode type in the config file to `playlist`.
