### ISSUE TITLE
File path errors

### ISSUE THREAD

**Issue by Neko-urself** [Guichaguri/DiscordDJ#34]
so basically, when you try to play a file and the path for the file has spaces.
Example:

http://puu.sh/nceOi/ab64540167.png

the path is supposed to be:
" E:\New folder\_music\Shibayan Records. . .. "

another example:

http://puu.sh/nceTB/38b3cb6a93.png

E:\LiGHt\osu!\Songs\59982 capitaro - Utatabigarasu\Utatabigarasu.mp3

Edit: i forgot to mention, i know the file thing works because when i tried playing an anime in mp4 format, it streamed the audio, pretty sick

**Comment by Guichaguri** [comment]
This one has already been fixed in 99ab4f8, but not released yet.
Duplicated from #28

**Comment by Guichaguri** [comment]
[v0.0.4](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.4) was released with the fix
