### ISSUE TITLE
Suggestion: Improve Discord playing status from the bot

### ISSUE THREAD

**Issue by ciruz** [Guichaguri/DiscordDJ#38]
Hey @Guichaguri,
maybe you can improve the discord status from the bot.

For example, if the bot plays no music, he should have a status like ```Nothing...``` instead of ```Music```
![bot playing no music](http://i.imgur.com/8GDaIh2.png)

If he starts playing music, he could show the song information as a status. I've made a small bot with discord.js and a video, to show you what I mean (watch the bots playing status), and you also see the ```!queue``` idea from my other suggestion #36 in this video:

![bot status updates](http://i.imgur.com/MLaJaJP.gif)

What do you think?

**Comment by SteamingMutt** [comment]
:+1:

**Comment by Guichaguri** [comment]
It's pretty easy to implement this, but the reason why I haven't done it yet is because the bot can play in multiple servers. I'll implement an option in the config file to achieve this result.

**Comment by Guichaguri** [comment]
Added in [v0.0.5](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.5)
