### ISSUE TITLE
Any way to play .m3u/Radionomy streams?

### ISSUE THREAD

**Issue by pankee** [Guichaguri/DiscordDJ#39]
I'm trying to play the following station with the bot: 
https://www.radionomy.com/en/radio/drive

There doesn't seem to be a way to play the stream with the link straight away, so I tried to download the .m3u file, and tried playing it with the /file command, but nothing happens.
It says it was added to the playlist, but the bot isn't playing it.

Is there any way to play streams other than Shoutcast/Icecast?

Thanks.

**Comment by Guichaguri** [comment]
Try `!icy http://streaming.radionomy.com/DRIVE`. It works for me.
I'm also fixing M3U playlists

**Comment by Guichaguri** [comment]
Fixed playlists in c0457dc53295ed02367dc1924014240c73c48ca8
