### ISSUE TITLE
FFmpeg

### ISSUE THREAD

**Issue by PlayRed** [Guichaguri/DiscordDJ#42]
First: "Encoder found."
and when I start music: "The encoder was not found."
![screenshot 27](https://cloud.githubusercontent.com/assets/17386156/13204004/fbb09d22-d8c4-11e5-9818-1dfb13be4b47.png)

**Comment by PlayRed** [comment]
how to fix it?

**Comment by Guichaguri** [comment]
For now you can add [FFmpeg to Path](http://www.wikihow.com/Install-FFmpeg-on-Windows)

**Comment by PlayRed** [comment]
I foud the mistake in the config I changed "encoder-path": "C:\\ffmpeg\\bin\\ffmpeg.exe", to "encoder-path": "C:\ffmpeg\bin\ffmpeg.exe",

now it works

**Comment by kevin8082** [comment]
Just out of curiosity, did you download with or without ffmpeg?
and the change you did looks like the same thing on both texts

**Comment by Guichaguri** [comment]
Fixed in [v0.0.5](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.5)
