### ISSUE TITLE
Crashes (a lot)

### ISSUE THREAD

**Issue by RoobieBoobieee** [Guichaguri/DiscordDJ#44]
I am currently testing your bot. I am experiencing the same crash listed below when trying to skip a song or when a song has the same amount of likes or dislikes as set in the config. Also you got a really nice 'Now Playing:' overview but i think it would be more convenient when its placed at the bottom of the chat again when a new song starts. 

Thank you very much. 
I'm sorry if this is issue already exists.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at Pipe.onread (net.js:544:26)

```

**Comment by ciruz** [comment]
I'm developing my own bot with discord.js and ytdl-core and experience the same bug with my bot.

I just had a small talk on https://github.com/hydrabolt/discord.js/issues/202 about the exact same problem and this is a ytdl-core problem.

https://github.com/hydrabolt/discord.js/issues/202
https://github.com/fent/node-ytdl-core/issues/65
https://github.com/meew0/Lethe/blob/master/lethe.js#L564

@Guichaguri can you check this out?

**Comment by Guichaguri** [comment]
I will use the same fix for now. Thanks
