### ISSUE TITLE
Bug !

### ISSUE THREAD

**Issue by Isharo** [Guichaguri/DiscordDJ#47]
http://i.imgur.com/4v7vBmm.png
@Guichaguri

**Comment by ciruz** [comment]
Please post your config file, you can censor your login. Thats not a bug. The config file is not correct.

**Comment by Isharo** [comment]
Where it is config file ?

**Comment by ciruz** [comment]
In the main directory of DiscordDJ its called ``config.json`` you can open it with a text editor. Post its content here, but please remove your email/password first.

**Comment by Isharo** [comment]
@ciruz I don't have config

http://i.imgur.com/ZKMjMev.png

**Comment by Isharo** [comment]
Can you send .zip bot ? @ciruz

**Comment by ciruz** [comment]
You can download the latest version ``0.0.4`` with ffmpeg for winodws [here](https://github.com/Guichaguri/DiscordDJ/releases/download/v0.0.4/windows-with-ffmpeg.zip) (~41mb), after extracting it you must run ``setup-bot.bat`` first to install and setup the bot.

**Comment by Isharo** [comment]
@ciruz I install 
and after "Y" the bot crashed

http://i.imgur.com/kvQpHrm.png

http://i.imgur.com/5wAcWrj.png

**Comment by Guichaguri** [comment]
You are using the latest commit. This is not recommended
Use a [released build](https://github.com/Guichaguri/DiscordDJ/releases) instead

**Comment by Isharo** [comment]
@Guichaguri I download windows with ffmpeg ?

**Comment by Guichaguri** [comment]
Windows with FFmpeg: for Windows and no need to install FFmpeg, because it is included
Windows without FFmpeg: for Windows
Other: for Linux/OS X
