### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Isharo** [Guichaguri/DiscordDJ#48]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.6.0
3 info using node@v5.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-dj@0.0.4~prestart: discord-dj@0.0.4
6 silly lifecycle discord-dj@0.0.4~prestart: no script for prestart, continuing
7 info lifecycle discord-dj@0.0.4~start: discord-dj@0.0.4
8 verbose lifecycle discord-dj@0.0.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-dj@0.0.4~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Corentin\Desktop\bbot\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Corentin\AppData\Roaming\npm
10 verbose lifecycle discord-dj@0.0.4~start: CWD: C:\Users\Corentin\Desktop\bbot
11 silly lifecycle discord-dj@0.0.4~start: Args: [ '/d /s /c', 'node ./runtime/DiscordDJ.js' ]
12 silly lifecycle discord-dj@0.0.4~start: Returned: code: 1  signal: null
13 info lifecycle discord-dj@0.0.4~start: Failed to exec start script
14 verbose stack Error: discord-dj@0.0.4 start: `node ./runtime/DiscordDJ.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid discord-dj@0.0.4
16 verbose cwd C:\Users\Corentin\Desktop\bbot
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.7.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error discord-dj@0.0.4 start: `node ./runtime/DiscordDJ.js`
22 error Exit status 1
23 error Failed at the discord-dj@0.0.4 start script 'node ./runtime/DiscordDJ.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-dj package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./runtime/DiscordDJ.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-dj
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-dj
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Guichaguri** [comment]
Can you give more information? When and how it happens?

**Comment by Isharo** [comment]
I have start "setup-bot" after start the bot crashed

**Comment by zjones89** [comment]
This also happens to me, you start the bot after installing it and it spits that error out and crashes, windows and linux both.

**Comment by ciruz** [comment]
This is a duplicate from #45.
