### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by EstherTMB** [Guichaguri/DiscordDJ#59]
After runing appers this

> ```
> C:\bot\runtime\DiscordDJ.js:33
>     if(!Utils.exists(config['decoder-path'])) {
>                            ^
> 
> TypeError: Cannot read property 'decoder-path' of null
>     at initDecoders (C:\bot\runtime\DiscordDJ.js:33:28)
>     at Object.<anonymous> (C:\bot\runtime\DiscordDJ.js:324:1)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Function.Module.runMain (module.js:447:10)
>     at startup (node.js:141:18)
>     at node.js:933:3
>  Для продолжения нажмите любую клавишу . . .
> ```

Maybe I'm doing something wrong.

**Comment by EstherTMB** [comment]
Oh. Sorry. I deal with it.

**Comment by EstherTMB** [comment]
Ok, I have another ploblem. I send him a link, bot writes me "You were added to the wait list and your track was set" and nothing happend. He's don't play.

**Comment by Guichaguri** [comment]
Duplicated to #50
