### ISSUE TITLE
Doesnt persist?

### ISSUE THREAD

**Issue by Fridgenz** [Guichaguri/DiscordDJ#6]
Hey, this idea is awesome, currently when i get everything installed and run it, it executes like a command but does not create the persistent bot, is this just the state of the bot thus far, or am i doing something wrong?

**Comment by dragsta** [comment]
Does the bot pop up in your discord chat?

**Comment by Fridgenz** [comment]
I realized i was using the current repo not the npm release

**Comment by Fridgenz** [comment]
Do you know what commands to use by any chance?

**Comment by Guichaguri** [comment]
Both of them are not stable yet. I'm working on it and in about one week it should be stable.

**Comment by Fridgenz** [comment]
Ive managed to get my bot to join voice and stuff, are there semi working commands that i can try use?

**Comment by dragsta** [comment]
Fridgenz Ive had the same problem i can't figure out any commands nor how to make them :/

**Comment by Fridgenz** [comment]
I can see that theyre registered to the bot, but dont know how to call them in chat

**Comment by Guichaguri** [comment]
I'm recoding the core functionality, the recode is almost done, that's why it's not usable yet

**Comment by Fridgenz** [comment]
Ok sweet, i found !add on the old version, but i get errors, i guess ill wait for a week or so

**Comment by Guichaguri** [comment]
Idk which version, but it should work something like `!add [youtube video url]`

**Comment by Fridgenz** [comment]
the version on npm
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn help ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
```
Get this when adding a youtube video to queue

**Comment by dragsta** [comment]
What does you prompt do after you load the bot? cause mine just sits there without giving any messages or anything. It does load into the voice chat on discord though.

**Comment by Guichaguri** [comment]
its a pretty old version on npm, I will update it once I make it work again

**Comment by Fridgenz** [comment]
@dragsta same, but typing !add [youtubelink] into a discord channel crashes the bot

**Comment by dragsta** [comment]
Hmm ok cool can't wait to see this fully working I'd offer to help but I'm not very versed in coding so it would probably be a setback not a help :)

**Comment by ripcrispy** [comment]
Hello @Guichaguri any updates on this issue by chance? I'm experiencing the same problems.

**Comment by Guichaguri** [comment]
Have you installed FFmpeg?

**Comment by ripcrispy** [comment]
Yeah, I've installed FFmpeg

**Comment by Guichaguri** [comment]
The first **development** build was released.
