### ISSUE TITLE
I try to click setup-bot.bat run through it then type Y, hit enter, then it crashes  in purple and red fireworks.

### ISSUE THREAD

**Issue by oremaster** [Guichaguri/DiscordDJ#82]
When I click setup-bot.bat, I run though all the things and they it goes to the part where it says "Run the bot now? [Y/N]" I hit the Y button then click enter. After that, lines of really fast text that are red and purple appear then crash. 
![image](https://cloud.githubusercontent.com/assets/23111877/19792090/0d5a3a76-9c7c-11e6-8ecd-12f8557dd529.png)

Edit: 
I read through what the purple and red said and it told me to paste this.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-dj@0.0.5~prestart: discord-dj@0.0.5
6 silly lifecycle discord-dj@0.0.5~prestart: no script for prestart, continuing
7 info lifecycle discord-dj@0.0.5~start: discord-dj@0.0.5
8 verbose lifecycle discord-dj@0.0.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-dj@0.0.5~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\tnguy_000\Desktop\DISCORDDJ\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Lenovo\FusionEngine;C:\Program Files (x86)\Intel\TXE Components\TCS\;C:\Program Files\Intel\TXE Components\TCS\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Lenovo\Bluetooth Software\;C:\Program Files\Lenovo\Bluetooth Software\syswow64;C:\Program Files (x86)\Lenovo\Motion Control\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\ffmpeg\bin
10 verbose lifecycle discord-dj@0.0.5~start: CWD: C:\Users\tnguy_000\Desktop\DISCORDDJ
11 silly lifecycle discord-dj@0.0.5~start: Args: [ '/d /s /c', 'node ./runtime/DiscordDJ.js' ]
12 silly lifecycle discord-dj@0.0.5~start: Returned: code: 1  signal: null
13 info lifecycle discord-dj@0.0.5~start: Failed to exec start script
14 verbose stack Error: discord-dj@0.0.5 start: `node ./runtime/DiscordDJ.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid discord-dj@0.0.5
16 verbose cwd C:\Users\tnguy_000\Desktop\DISCORDDJ
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.0.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error discord-dj@0.0.5 start: `node ./runtime/DiscordDJ.js`
22 error Exit status 1
23 error Failed at the discord-dj@0.0.5 start script 'node ./runtime/DiscordDJ.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-dj package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./runtime/DiscordDJ.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-dj
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-dj
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Guichaguri** [comment]
DiscordDJ is currently being recoded. The last version doesn't work anymore since the official Discord API was released.
