### ISSUE TITLE
Help! Commands are not accepted

### ISSUE THREAD

**Issue by kevinixz** [Guichaguri/DiscordDJ#83]
I followed all the steps, but when I try to send inbox commands like /add www.youtube....... or any other command.....

> Trying to connect...
> Connected! Initializing the DJs...
> Initializing DJ in "Homies"
> Config saved!
> New update available!
> DiscordDJ v0.1.0
> http://guichaguri.github.io/DiscordDJ/
> A command threw an error (add): TypeError: Promise.accept is not a function
> A command threw an error (add): TypeError: Promise.accept is not a function
> A command threw an error (yt): TypeError: Promise.accept is not a function
>

**Comment by Guichaguri** [comment]
DiscordDJ is currently being recoded. The last version doesn't work anymore since the official Discord API was released.
