### ISSUE TITLE
setup-bot.bat Error

### ISSUE THREAD

**Issue by JhonforgeGaming** [Guichaguri/DiscordDJ#84]
It Says:"Run the bot now? [Y/N]Y

> discord-dj@0.0.5 start F:\Programs
> node ./runtime/DiscordDJ.js

F:\Programs\runtime\DiscordDJ.js:33
    if(!Utils.exists(config['decoder-path'])) {
                           ^

TypeError: Cannot read property 'decoder-path' of null
    at initDecoders (F:\Programs\runtime\DiscordDJ.js:33:28)
    at Object.<anonymous> (F:\Programs\runtime\DiscordDJ.js:324:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! discord-dj@0.0.5 start: `node ./runtime/DiscordDJ.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-dj@0.0.5 start script 'node ./runtime/DiscordDJ.j
s'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the discord-dj package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./runtime/DiscordDJ.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discord-dj
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls discord-dj
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Programs\npm-debug.log

F:\Programs>"
What does this mean and how do I fix this?

**Comment by Guichaguri** [comment]
Since the Discord API was released, the old DiscordDJ version stopped working. I'm currently recoding DiscordDJ, but it takes time, sorry.

Duplicates #82

**Comment by JhonforgeGaming** [comment]
ah ok. I totally get the takes time part since I code as well just not Javascript.
