### ISSUE TITLE
Unusable?

### ISSUE THREAD

**Issue by midnightmythix** [Guichaguri/DiscordDJ#87]
I get an error whenever I attempt to run DiscordDJ.js .
![screen shot 2016-11-22 at 7 03 16 pm](https://cloud.githubusercontent.com/assets/22209348/20546920/61b5e150-b0e6-11e6-8393-aebf2ce0ba70.png)

**Comment by Guichaguri** [comment]
DiscordDJ is broken since the official Discord API was released. I'm currently recoding it, but it's not yet ready to use. Sorry for the inconvenience.
