### ISSUE TITLE
One positive appinion

### ISSUE THREAD

**Issue by lZzozZl** [Guichaguri/DiscordDJ#89]
HI. I'm not using your bot but i will test it when its ready :)
You are doing great bot with great ideas and i hope many more people will download it and think like me as well.

Take your time and don't rush it. People always will ask from you to do stuff because they cant. You are great person for doing that bot without asking people for things in return. I wish you luck in your in your life, work and in every possible way :)

Thanks again for your work!

Best regards
Random Person :)

**Comment by Guichaguri** [comment]
Thank you, I really appreciate it :)
I plan to get back into developing it once I finish other projects, I still have a lot of ideas for this project...
It's really nice of you sending a positive message to an almost dead project, thank you :)

**Comment by lZzozZl** [comment]
No problem. I hope this message motivate you. Wish you best man :)
